import type { Metadata } from "next";
import { Geist_Mono, Silkscreen } from "next/font/google";
import "@/assets/global.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const silkscreen = Silkscreen({
  variable: "--font-silkscreen",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arisevan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${silkscreen.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 z-[-1] w-screen h-screen bg-[url(/common/bg.svg)]"></div>
        {children}
      </body>
    </html>
  );
}
